name: CI Tests

on: [pull_request,push]

jobs:
  Ubuntu:

    runs-on: ubuntu-20.04

    name: Ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake ..

      - name: Building
        run: |
          make -j$(nproc) -C build

  MSVC:

    runs-on: windows-latest

    name: Windows MSVC

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring
        run: |
          mkdir build; cd build
          cmake ..

      - name: Building
        run: |
          cmake --build build --config Debug -- -maxCpuCount

  macos:

    runs-on: macos-latest

    name: macos

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake ..

      - name: Building
        run: |
          make -j$(sysctl -n hw.logicalcpu) -C build
