name: CI Tests

on: [pull_request,push]

jobs:
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON

      - name: Building
        run: |
          make -j$(nproc) -C build

  MSVC:
    name: Windows MSVC
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        shared: [ON, OFF]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring
        run: |
          mkdir build; cd build
          cmake .. `
            -DBUILD_SHARED_LIBS=${{ matrix.shared }}

      - name: Building
        run: |
          cmake --build build --config Debug -- -maxCpuCount

  macos:
    name: macos
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake ..

      - name: Building
        run: |
          make -j$(sysctl -n hw.logicalcpu) -C build
